version: '3.8'

services:
  joomla:
    image: joomla
    volumes:
       - db_data:/var/lib/mysql
    ports:
      - "8080:80"
    restart: always
    environment:
      JOOMLA_DB_HOST: db:3306
      JOOMLA_DB_USER: joomla
      JOOMLA_DB_PASSWORD: joomla
      JOOMLA_DB_NAME: joomla
    depends_on:
      - db

  db:
    image: mysql:8.2
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: joomla
      MYSQL_USER: joomla
      MYSQL_PASSWORD: joomla
    ports:
      - "3306:3306"
volumes:
    db_data: {}